### ISSUE TITLE
Do not eliminate `/usr/local/include` as an include directory for `clang` on `macOS`

### ISSUE THREAD

**Issue by mmomtchev** [mmomtchev/hadron#37]
**Describe the bug**
Do not eliminate `/usr/local/include` as an include directory for `clang` on `macOS`.
Not all versions of `clang` include it by default.

**To Reproduce**
`clang` in GHA seems to come from homebrew and does not include it.
```c
#include <X11/Xos.h>

int main() {
  return 0;
}
```

```yaml
- run: clang -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -o test_include test_include.c
- run: clang -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -I/usr/local/include -o test_include test_include.c
- run: clang -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -isystem/usr/local/include -o test_include test_include.c
```

**Expected behavior**
Treat `/usr/local/include` as a custom directory

**system parameters**
`macos-12` runner on GHA
